name: Android CI

on:
  push:
    branches: [ main ]  # 推送至 main 分支时触发
  pull_request:
    branches: [ main ]  # 针对 main 的 PR 时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      # 2. 设置 JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. 授予 Gradle 执行权限
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # 4. 构建 Release APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # 5. 上传 APK 为工作流产物（可选）
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk